<a href="https://colab.research.google.com/github/SandraReine/Python-Basics-Projects-Repo/blob/main/Pandas_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(student.csv)

In [ ]:
df = pd.read_excel("student.xlsx")

In [ ]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
df.id

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
Name: id, dtype: int64

In [ ]:
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.tail(10)

    id         name  class  mark  gender
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.sample()

    id  name  class  mark  gender
13  14  Bigy  Seven    88  female

In [ ]:
df.sample(3)

    id       name  class  mark  gender
23  24  Tiddy Now  Seven    78    male
9   10   Big John   Four    55  female
12  13        Kty  Seven    88  female

In [ ]:
df.shape

(35, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

compare non-null count vs number of entries. If there is a difference, there is a missing value.
name column has a missing value
gender column has 2 missing values
class column has a missing value

number of entries
datatype
non-null count
object64 is a string column

In [ ]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
len(df)

35

In [ ]:
df.size

175

In [ ]:
df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.id

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
Name: id, dtype: int64

In [ ]:
df["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
Name: id, dtype: int64

In [ ]:
df.name

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df.class

SyntaxError: invalid syntax (1584895042.py, line 1)

In [ ]:
df["class"]

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14      NaN
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, dtype: object

In [ ]:
df.gender

0     female
1       male
2       male
3     female
4     female
5       male
6       male
7       male
8        NaN
9     female
10    female
11    female
12    female
13    female
14      male
15      male
16      male
17      male
18      male
19    female
20    female
21    female
22      male
23      male
24      male
25      male
26       NaN
27    female
28      male
29    female
30      male
31    female
32    female
33      male
34    female
Name: gender, dtype: object

In [ ]:
df["gender"]

0     female
1       male
2       male
3     female
4     female
5       male
6       male
7       male
8        NaN
9     female
10    female
11    female
12    female
13    female
14      male
15      male
16      male
17      male
18      male
19    female
20    female
21    female
22      male
23      male
24      male
25      male
26       NaN
27    female
28      male
29    female
30      male
31    female
32    female
33      male
34    female
Name: gender, dtype: object

In [ ]:
df["gender"].head()

0    female
1      male
2      male
3    female
4    female
Name: gender, dtype: object

In [ ]:
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
df["mark"].median()

79.0

In [ ]:
df[["name","class"]]

In [ ]:
df[["name","gender"]]

           name  gender
0      John Deo  female
1      Max Ruin    male
2        Arnold    male
3    Krish Star  female
4     John Mike  female
5     Alex John    male
6   My John Rob    male
7        Asruid    male
8       Tes Qry     NaN
9      Big John  female
10       Ronald  female
11        Recky  female
12          Kty  female
13         Bigy  female
14     Tade Row    male
15        Gimmy    male
16        Tumyu    male
17        Honny    male
18        Tinny    male
19       Jackly  female
20   Babby John  female
21       Reggid  female
22        Herod    male
23    Tiddy Now    male
24     Giff Tow    male
25       Crelea    male
26          NaN     NaN
27    Rojj Base  female
28  Tess Played    male
29    Reppy Red  female
30  Marry Toeey    male
31    Binn Rott  female
32    Kenn Rein  female
33     Gain Toe    male
34   Rows Noump  female

In [ ]:
df[["id","name","gender"]]

    id         name  gender
0    1     John Deo  female
1    2     Max Ruin    male
2    3       Arnold    male
3    4   Krish Star  female
4    5    John Mike  female
5    6    Alex John    male
6    7  My John Rob    male
7    8       Asruid    male
8    9      Tes Qry     NaN
9   10     Big John  female
10  11       Ronald  female
11  12        Recky  female
12  13          Kty  female
13  14         Bigy  female
14  15     Tade Row    male
15  16        Gimmy    male
16  17        Tumyu    male
17  18        Honny    male
18  19        Tinny    male
19  20       Jackly  female
20  21   Babby John  female
21  22       Reggid  female
22  23        Herod    male
23  24    Tiddy Now    male
24  25     Giff Tow    male
25  26       Crelea    male
26  27          NaN     NaN
27  28    Rojj Base  female
28  29  Tess Played    male
29  30    Reppy Red  female
30  31  Marry Toeey    male
31  32    Binn Rott  female
32  33    Kenn Rein  female
33  34     Gain Toe    male
34  35   Rows Noump  female

In [ ]:
df[["id","name","gender"]].head()

   id        name  gender
0   1    John Deo  female
1   2    Max Ruin    male
2   3      Arnold    male
3   4  Krish Star  female
4   5   John Mike  female

In [ ]:
df[["id","name","gender"]].sample()

    id        name  gender
34  35  Rows Noump  female

In [ ]:
df[["name","class"]].info

<bound method DataFrame.info of            name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
5     Alex John   Four
6   My John Rob  Fifth
7        Asruid   Five
8       Tes Qry    Six
9      Big John   Four
10       Ronald    Six
11        Recky    Six
12          Kty  Seven
13         Bigy  Seven
14     Tade Row    NaN
15        Gimmy   Four
16        Tumyu    Six
17        Honny   Five
18        Tinny   Nine
19       Jackly   Nine
20   Babby John   Four
21       Reggid  Seven
22        Herod  Eight
23    Tiddy Now  Seven
24     Giff Tow  Seven
25       Crelea  Seven
26          NaN  Three
27    Rojj Base  Seven
28  Tess Played  Seven
29    Reppy Red    Six
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six>

In [ ]:
df[["id","name","gender"]].sample()

   id    name gender
7   8  Asruid   male

In [ ]:
df[["name","class","gender"]]

           name  class  gender
0      John Deo   Four  female
1      Max Ruin  Three    male
2        Arnold  Three    male
3    Krish Star   Four  female
4     John Mike   Four  female
5     Alex John   Four    male
6   My John Rob  Fifth    male
7        Asruid   Five    male
8       Tes Qry    Six     NaN
9      Big John   Four  female
10       Ronald    Six  female
11        Recky    Six  female
12          Kty  Seven  female
13         Bigy  Seven  female
14     Tade Row    NaN    male
15        Gimmy   Four    male
16        Tumyu    Six    male
17        Honny   Five    male
18        Tinny   Nine    male
19       Jackly   Nine  female
20   Babby John   Four  female
21       Reggid  Seven  female
22        Herod  Eight    male
23    Tiddy Now  Seven    male
24     Giff Tow  Seven    male
25       Crelea  Seven    male
26          NaN  Three     NaN
27    Rojj Base  Seven  female
28  Tess Played  Seven    male
29    Reppy Red    Six  female
30  Marry Toeey   Four    male
31    Binn Rott  Seven  female
32    Kenn Rein    Six  female
33     Gain Toe  Seven    male
34   Rows Noump    Six  female

In [ ]:
df.query("mark > 80")

    id         name  class  mark  gender
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
24  25     Giff Tow  Seven    88    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [ ]:
df.loc[3,"name"]

'Krish Star'

In [ ]:
df.loc[25,"mark"]

np.int64(79)

In [ ]:
df.iloc[3,1]

'Krish Star'

In [ ]:
df.iloc[25,3]

np.int64(79)

In [ ]:
df.loc[3,["name","gender"]]

name      Krish Star
gender        female
Name: 3, dtype: object

In [ ]:
df.iloc[3,[1,4]]

name      Krish Star
gender        female
Name: 3, dtype: object

In [ ]:
df.loc[[5,15,25],["name","class"]]

         name  class
5   Alex John   Four
15      Gimmy   Four
25     Crelea  Seven

In [ ]:
df.iloc[[5,15,25],[1,2]]

         name  class
5   Alex John   Four
15      Gimmy   Four
25     Crelea  Seven

In [ ]:
df.loc[1:4,["name","mark"]]

         name  mark
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60
4   John Mike    60

In [ ]:
df.iloc[1:4,[1,3]]

         name  mark
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60

In [ ]:
df.loc[1:4,1]

In [ ]:
df["mark"]>90

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
Name: mark, dtype: bool

In [ ]:
df[df["mark"] ==90]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
31,32,Binn Rott,Seven,90,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df[df["gender"]=="female"]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
0,1,John Deo,Four,75,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
3,4,Krish Star,Four,60,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
4,5,John Mike,Four,60,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
9,10,Big John,Four,55,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
10,11,Ronald,Six,89,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
11,12,Recky,Six,94,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
12,13,Kty,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
13,14,Bigy,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
19,20,Jackly,Nine,65,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
20,21,Babby John,Four,69,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
21,22,Reggid,Seven,55,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
27,28,Rojj Base,Seven,86,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
29,30,Reppy Red,Six,79,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
31,32,Binn Rott,Seven,90,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
32,33,Kenn Rein,Six,96,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
34,35,Rows Noump,Six,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df[(df["gender"]== "male") & (df["class"]== "four")]

Empty DataFrame
Columns: [id, name, class, mark, gender, 75, 85, 55, 60, 78, 89, 94, 88, 54, 18, 65, 69, 79, 81, 86, 90, 96]
Index: []

[0 rows x 22 columns]

In [ ]:
df[(df["mark"]<90) & (df["gender"]=="female")]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
0,1,John Deo,Four,75,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
3,4,Krish Star,Four,60,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
4,5,John Mike,Four,60,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
9,10,Big John,Four,55,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
10,11,Ronald,Six,89,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
12,13,Kty,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
13,14,Bigy,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
19,20,Jackly,Nine,65,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
20,21,Babby John,Four,69,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
21,22,Reggid,Seven,55,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
27,28,Rojj Base,Seven,86,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
29,30,Reppy Red,Six,79,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
34,35,Rows Noump,Six,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df[df["gender"]=="female"]["mark"].mean()

np.float64(77.3125)

In [ ]:
df[(df["mark"]>90) | (df["gender"]=="male")]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
1,2,Max Ruin,Three,85,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
2,3,Arnold,Three,55,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
5,6,Alex John,Four,55,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
6,7,My John Rob,Fifth,78,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
7,8,Asruid,Five,85,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
11,12,Recky,Six,94,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
14,15,Tade Row,NaN,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
15,16,Gimmy,Four,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
16,17,Tumyu,Six,54,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
17,18,Honny,Five,75,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
18,19,Tinny,Nine,18,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
22,23,Herod,Eight,79,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
23,24,Tiddy Now,Seven,78,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
24,25,Giff Tow,Seven,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
25,26,Crelea,Seven,79,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
28,29,Tess Played,Seven,55,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
30,31,Marry Toeey,Four,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
32,33,Kenn Rein,Six,96,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
33,34,Gain Toe,Seven,69,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
df["mark"].max()

96

In [ ]:
df["mark"].min()

18

In [ ]:
df.filter(items=['male','mark']).mean()

mark    74.657143
dtype: float64

In [ ]:
df.loc[df["mark"]>90, :]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
11,12,Recky,Six,94,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
32,33,Kenn Rein,Six,96,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df.loc[df["mark"]>90,:]

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
11,12,Recky,Six,94,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
32,33,Kenn Rein,Six,96,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df.loc[(df["mark"]>80) & (df["class"]=="Five"), ["name", "mark"]]

     name  mark
7  Asruid    85

In [ ]:
df.iloc[df["mark"]>90, :]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [ ]:
df.filter(items=['name', 'mark'])

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.filter(like='ma').head()

   mark
0    75
1    85
2    55
3    60
4    60

In [ ]:
 df.query("mark > 80")

,id,name,class,mark,gender,75,85,55,60,78,...,88,54,18,65,69,79,81,86,90,96
1,2,Max Ruin,Three,85,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
7,8,Asruid,Five,85,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
10,11,Ronald,Six,89,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
11,12,Recky,Six,94,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
12,13,Kty,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
13,14,Bigy,Seven,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
14,15,Tade Row,NaN,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
15,16,Gimmy,Four,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
24,25,Giff Tow,Seven,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
26,27,NaN,Three,81,NaN,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
27,28,Rojj Base,Seven,86,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
30,31,Marry Toeey,Four,88,male,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
31,32,Binn Rott,Seven,90,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
32,33,Kenn Rein,Six,96,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90
34,35,Rows Noump,Six,88,female,90,90,90,90,90,...,90,90,90,90,90,90,90,90,90,90

In [ ]:
df.filter(items=['female', 'mark'])mean()

In [ ]:
df.head ('mark').mean()

In [ ]:
df[df["gender"]=="female"]["mark"].mean()

np.float64(77.3125)

In [ ]:
df[df["gender"]=="female"]["mark"].mean()

np.float64(77.3125)

In [ ]:
(df["class"]=="Five")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
Name: class, dtype: bool

In [ ]:
df.sort_values(by="name")

    id         name  class  mark  gender
5    6    Alex John   Four    55    male
2    3       Arnold  Three    55    male
7    8       Asruid   Five    85    male
20  21   Babby John   Four    69  female
9   10     Big John   Four    55  female
13  14         Bigy  Seven    88  female
31  32    Binn Rott  Seven    90  female
25  26       Crelea  Seven    79    male
33  34     Gain Toe  Seven    69    male
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
22  23        Herod  Eight    79    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
0    1     John Deo   Four    75  female
4    5    John Mike   Four    60  female
32  33    Kenn Rein    Six    96  female
3    4   Krish Star   Four    60  female
12  13          Kty  Seven    88  female
30  31  Marry Toeey   Four    88    male
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
11  12        Recky    Six    94  female
21  22       Reggid  Seven    55  female
29  30    Reppy Red    Six    79  female
27  28    Rojj Base  Seven    86  female
10  11       Ronald    Six    89  female
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
8    9      Tes Qry    Six    78     NaN
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
26  27          NaN  Three    81     NaN

In [ ]:
df.sort_values(by="mark")

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
28  29  Tess Played  Seven    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
23  24    Tiddy Now  Seven    78    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df.sort_values(by="mark", ascending=False)

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male
34  35   Rows Noump    Six    88  female
24  25     Giff Tow  Seven    88    male
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
19  20       Jackly   Nine    65  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [ ]:
df.sort_values(by="class")

    id         name  class  mark  gender
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
17  18        Honny   Five    75    male
7    8       Asruid   Five    85    male
30  31  Marry Toeey   Four    88    male
20  21   Babby John   Four    69  female
15  16        Gimmy   Four    88    male
9   10     Big John   Four    55  female
0    1     John Deo   Four    75  female
5    6    Alex John   Four    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
18  19        Tinny   Nine    18    male
12  13          Kty  Seven    88  female
33  34     Gain Toe  Seven    69    male
25  26       Crelea  Seven    79    male
31  32    Binn Rott  Seven    90  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female
8    9      Tes Qry    Six    78     NaN
16  17        Tumyu    Six    54    male
11  12        Recky    Six    94  female
10  11       Ronald    Six    89  female
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
2    3       Arnold  Three    55    male
14  15     Tade Row    NaN    88    male

In [ ]:
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df.loc[:,:].sort_values(by= ["mark", "class"])

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
22  23        Herod  Eight    79    male
25  26       Crelea  Seven    79    male
29  30    Reppy Red    Six    79  female
26  27          NaN  Three    81     NaN
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
27  28    Rojj Base  Seven    86  female
15  16        Gimmy   Four    88    male
30  31  Marry Toeey   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
24  25     Giff Tow  Seven    88    male
34  35   Rows Noump    Six    88  female
14  15     Tade Row    NaN    88    male
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64